services:
  build:
    image: ghcr.io/sergiuchilat/next-build-test/front:dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    profiles:
      - build
  run:
    image: ghcr.io/sergiuchilat/next-build-test/front:dev
    profiles:
      - run
    ports:
      - "3000:3000"

